package it.veneto.regione.aagg.web.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import it.veneto.regione.aagg.web.AppaltoRepository;
import it.veneto.regione.aagg.web.DipendenteRepository;
import it.veneto.regione.aagg.web.model.Appalto;

@Controller
public class GreetingController {

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired 
    private DipendenteRepository dipendenteRepository;
    @Autowired 
    private AppaltoRepository appaltoRepository;
    
    
	@GetMapping("/greeting")
	public String greeting(@RequestParam(name="name", required=false, defaultValue="World") String name, Model model) {
		model.addAttribute("name", name);
		return "greeting";
	}
	
	@GetMapping(path="/dipendenti")
	public //@ResponseBody Iterable<Dipendenti>
	   ModelAndView 
	   getAllDipendenti() {
	    // This returns a JSON or XML with the users
	    ModelAndView mav = new ModelAndView("lista-dipendenti");
		mav.addObject("dipendenti", dipendenteRepository.findDipendentiMatricolaAsc());
		return mav;
	}
	
	@GetMapping(path="/appalti")
	public ModelAndView getAllAppalti() {
	    // This returns a JSON or XML with the users
	    ModelAndView mav = new ModelAndView("lista-appalti");
	    Iterable<Appalto> appalti = appaltoRepository.findAll(Sort.by("dataFine").ascending().and(Sort.by("dataInizio").ascending()));
	    //Iterable<Appalto> appalti = appaltoRepository.findApertiMatricolaNative(906); 
		mav.addObject("appalti", appalti);
		return mav;
	}
	
	@GetMapping(path="/appalti/ballan")
	public ModelAndView getAllAppaltiBallan() {
	    // This returns a JSON or XML with the users
	    ModelAndView mav = new ModelAndView("lista-appalti-ballan");
	    //Iterable<Appalto> appalti = appaltoRepository.findAll(Sort.by("dataFine").ascending().and(Sort.by("dataInizio").ascending()));
	    Iterable<Appalto> appalti = appaltoRepository.findApertiMatricolaNative(906); 
		mav.addObject("appalti", appalti);
		return mav;
	}
	
	@GetMapping(path="/appalti/gallina")
	public ModelAndView getAllAppaltiGallina() {
	    // This returns a JSON or XML with the users
	    ModelAndView mav = new ModelAndView("lista-appalti-gallina");
	    Iterable<Appalto> appalti = appaltoRepository.findApertiMatricolaNative(10225); 
		mav.addObject("appalti", appalti);
		return mav;
	}
	
	@GetMapping(path="/appalti/consoletti")
	public ModelAndView getAllAppaltiConsoletti() {
	    // This returns a JSON or XML with the users
	    ModelAndView mav = new ModelAndView("lista-appalti-consoletti");
	    Iterable<Appalto> appalti = appaltoRepository.findApertiMatricolaNative(103138); 
		mav.addObject("appalti", appalti);
		return mav;
	}
}